app1/urls.py
from app1.views import *
from django.urls import path

app_name='app1'

urlpatterns=[
    path('first/',first,name="first"),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('second/',second,name='second')
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.


def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.


def second(request):
    return render(request,'second.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS THE FIRST PAGE OF SPCIFIC URL NAVIGATION</h1>
        <h2>THIS IS DONE IN APP1</h2>
        <a href="{% url 'app2:second' %}"><h1>click here to go second page</h1></a>

    </center>
    
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS THE SECOND PAGE OF SPECIFIC URL MAPPING</h1>
        <h2>THIS IS DONE IN APP2</h2>
        <a href="{% url 'app1:first' %}"><h1>click here to go first page</h1></a>
    </center>
</body>
</html>